config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "restaurants#index"

  resources :restaurants, only: %i[index]
  resources :selections, only: %i[index]
  resources :users do
    resources :places
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true, allow_blank: false
  validates :address, presence: true, allow_blank: false
  validates :city, presence: true, allow_blank: false

  has_many :places
  has_many :users, through: :places

  def map_link
    "https://www.google.com/maps?q=#{lat},#{lon}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places
  has_many :restaurants, through: :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    selections_path
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, :user, :restaurants, :check_user

  def index
    if params[:query].present?
      @restaurants = @restaurants.where("name LIKE ?", "%#{params[:query]}%")
    end
    @places = user.places
  end

  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to selections_path, notice: "Restaurant added" }
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @place = user.places.find_by(id: params[:id])
    if @place&.destroy
      redirect_to selections_url, notice: "Selection was successfully deleted."
    end
  end

  private

  def user
    @user = User.find(params[:user_id])
  end

  def check_user
    redirect_to selections_url unless current_user.id == user.id
  end

  def restaurants
    @restaurants = Restaurant.all
  end

  def place_params
    params.permit(:user_id, :restaurant_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :restaurants, only: %i[ index ] 

  def index
    if params[:query].present?
      @restaurants = @restaurants.where("name LIKE ?", "%#{params[:query]}%")
    end

    if turbo_frame_request?
      render partial: "restaurants", locals: { restaurants: @restaurants }
    else
      render "index"
    end
  end

  private

  def restaurants
    @restaurants = Restaurant.all
  end
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @places = current_user.places
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lunch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %> 
      <div class="flex items-center">
      <%= button_to "Home", "/", method: :get, class: "btn py-2 ml-2 bg-green-300" %> 
      <%= button_to "Selection", selections_path, method: :get, class: "btn py-2 ml-2 bg-blue-300" %> 
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn py-2 ml-2 bg-red-300" %> 
      </div>
    <% else %>
      <%= button_to "Sign in", new_user_session_path, class: "btn py-2 ml-2 bg-blue-300" %> 
    <% end %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/places/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <span>
    <%= restaurant.name %>
    <a href=<%= restaurant.map_link %> class="font-medium text-blue-600 dark:text-blue-500 hover:underline" target="_blank"><%= restaurant.address %></a>
    +
  </span>
</div>

app/views/places/_restaurants.html.erb
<%= turbo_frame_tag "restaurants" do %>
  <%= render restaurants %>
<% end %>

app/views/places/index.html.erb
<h1 class="font-bold text-3xl">Restaurants Selection</h1>

<div class="mt-4">
<%= form_with(url: user_places_path(user_id: current_user.id), method: "GET", data: { turbo_frame: "restaurants" }, class: 'mb-7') do |form| %>
  <%= form.text_field :query %>
  <%= form.submit 'Search', name: nil, class: "btn py-2 ml-2 bg-blue-300" %>
<% end %>
<%= render "restaurants", restaurants: @restaurants %>
</div>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>" class="block">
  <span>
    <%= restaurant.name %>
    <a href=<%= restaurant.map_link %> class="font-medium text-blue-600 dark:text-blue-500 hover:underline" target="_blank"><%= restaurant.address %></a>
  </span>
    <% if current_user && request.original_url.include?('places') %>
      <div class="inline-block ml-2">
      <%= button_to "+", user_places_path(user_id: current_user.id, restaurant_id: restaurant.id), method: :post, data: {turbo_frame: "_top"}, class: "btn py-2 ml-2 bg-green-300" %> 
      </div>
    <% end %>
</div>

app/views/restaurants/_restaurants.html.erb
<%= turbo_frame_tag "restaurants" do %>
  <%= render restaurants %>
<% end %>

app/views/restaurants/index.html.erb
<h1 class="font-bold text-6xl">Restaurants</h1>

<div class="mt-4">
  <%= form_with(url: restaurants_path, method: "GET", data: { turbo_frame: "restaurants" }, class: 'mb-7') do |form| %>
    <%= form.text_field :query %>
    <%= form.submit 'Search', name: nil, class: "btn py-2 ml-2 bg-green-300" %>
  <% end %>
  <%= render "restaurants", restaurants: @restaurants %>
</div>

app/views/selections/_places.html.erb
<table>
  <thead>
    <tr>
      <th>
        <%= link_to "See the list of restaurants to select", user_places_path(user_id: current_user.id), method: :get, class: "btn mb-3 bg-gray-100" %>
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% places.each do |place| %>
      <tr>
        <td><%= place.restaurant.name %></td>
        <td><%= place.restaurant.address %></td>
        <td><%= button_to "Delete", user_place_path(user_id: current_user.id, id: place.id), method: :delete, class: "btn mb-3 bg-red-300" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/selections/index.html.erb
<h1 class="font-bold text-6xl"> Selection </h1>

<% if @places.any? %>
  <%= render "places", places: @places %>
<% else %>
  <%= link_to "Create a list of restaurants", user_places_path(user_id: current_user.id), class: "btn mb-3 bg-gray-100" %>
<% end %>